[package]
name = "lista3"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
blake3 = "1.5.0"
rand = "0.8.5"
rand_pcg = "0.3.1"
